=== cn-cerc/summer-watchdog/src/main/resources/app-roles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:include schemaLocation="app-versions.xsd"></xs:include>
    <xs:element name="html" type="RoleFile" />
    <xs:complexType name="RoleFile">
        <xs:sequence>
            <xs:element name="head" type="MenuHead" />
            <xs:element name="body" type="RoleBody" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MenuHead">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <!-- <xs:element name="system" type="MenuSystem"/> -->
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RoleBody">
        <xs:sequence>
            <xs:element name="security" type="ProcItem" minOccurs="0" maxOccurs="unbounded" />
            <!-- <xs:element name="item" type="MenuItem" minOccurs="0" maxOccurs="unbounded"/> -->
            <!-- <xs:element name="section" type="MenuSection" maxOccurs="unbounded"/> -->
        </xs:sequence>
        <!-- <xs:attribute name="mapfile" type="xs:string" use="required" /> -->
    </xs:complexType>
    <xs:complexType name="ProcAccess">
        <xs:sequence>
            <xs:element name="group" type="AccessGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="verlist" type="VerList" use="required" />
    </xs:complexType>
    <xs:complexType name="AccessGroup">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="GroupItem" />
                <xs:attribute name="Execute" type="xs:boolean" />
                <xs:attribute name="Final" type="xs:boolean" />
                <xs:attribute name="Append" type="xs:boolean" />
                <xs:attribute name="Modify" type="xs:boolean" />
                <xs:attribute name="Delete" type="xs:boolean" />
                <xs:attribute name="Print" type="xs:boolean" />
                <xs:attribute name="PrintSet" type="xs:boolean" />
                <xs:attribute name="Cancel" type="xs:boolean" />
                <xs:attribute name="MoneyDisplay" type="xs:boolean" />
                <xs:attribute name="MoneyModify" type="xs:boolean" />
                <xs:attribute name="Output" type="xs:boolean" />
                <xs:attribute name="FreeFlow" type="xs:boolean" />
                <xs:attribute name="DownFile" type="xs:boolean" />
                <xs:attribute name="ShareMyData" type="xs:boolean" />
                <xs:attribute name="Recycle" type="xs:boolean" />
                <xs:attribute name="ReadCED" type="xs:boolean" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="GroupItem">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SCM101" />
            <xs:enumeration value="SCM102" />
            <xs:enumeration value="SCM103" />
            <xs:enumeration value="SCM104" />
            <xs:enumeration value="SCM105" />
            <xs:enumeration value="SCM106" />
            <xs:enumeration value="SCM107" />
            <xs:enumeration value="SCM108" />
            <xs:enumeration value="SCM199" />
            <xs:enumeration value="SCM201" />
            <xs:enumeration value="SCM202" />
            <xs:enumeration value="SCM203" />
            <xs:enumeration value="SCM204" />
            <xs:enumeration value="SCM205" />
            <xs:enumeration value="SCM299" />
            <xs:enumeration value="SCM301" />
            <xs:enumeration value="SCM302" />
            <xs:enumeration value="SCM303" />
            <xs:enumeration value="SCM399" />
            <xs:enumeration value="SCM001" />
            <xs:enumeration value="SCM002" />
            <xs:enumeration value="SCM401" />
            <xs:enumeration value="SCM402" />
            <xs:enumeration value="SCM403" />
            <xs:enumeration value="SCM404" />
            <xs:enumeration value="SCM405" />
            <xs:enumeration value="SCM406" />
            <xs:enumeration value="SCM407" />
            <xs:enumeration value="SCM408" />
            <xs:enumeration value="SCM409" />
            <xs:enumeration value="SCM410" />
            <xs:enumeration value="SCM411" />
            <xs:enumeration value="SCM412" />
            <xs:enumeration value="SCM413" />
            <xs:enumeration value="SCM499" />
            <xs:enumeration value="SCM501" />
            <xs:enumeration value="SCM601" />
            <xs:enumeration value="SCM602" />
            <xs:enumeration value="SCM603" />
            <xs:enumeration value="SCM604" />
            <xs:enumeration value="SCM699" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ProcItem">
        <xs:sequence>
            <xs:element name="access" type="ProcAccess" />
        </xs:sequence>
        <xs:attribute name="code" type="ProcCode" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="group" type="ProcGroup" use="required" />
        <xs:attribute name="type" type="ProcType" use="required" />
    </xs:complexType>
    <xs:simpleType name="ProcGroup">
        <xs:restriction base="xs:string">
            <xs:enumeration value="service" />
            <xs:enumeration value="base" />
            <xs:enumeration value="purchase" />
            <xs:enumeration value="sell" />
            <xs:enumeration value="stock" />
            <xs:enumeration value="acc" />
            <xs:enumeration value="other" />
            <xs:enumeration value="conn" />
            <xs:enumeration value="make" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ProcType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="execute" />
            <xs:enumeration value="report" />
            <xs:enumeration value="record" />
            <xs:enumeration value="form" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== cn-cerc/summer-watchdog/src/main/resources/app-roles.xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="app-roles.xsd">
    <head>
        <title>地藤系统菜单库</title>
    </head>
    <body>
        <security code="service.base.options" name="系统运行选项设置" type="record" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="service.book.manage" name="帐套建立与管理" type="record" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="service.charge.manage" name="藤币充值管理" type="record" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="service.data.backup" name="资料备份与还原" type="execute" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="service.data.manage" name="系统数据结构管理" type="record" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="service.run.view" name="系统运行状态查询" type="report" group="service">
            <access verlist="0,">
                <group code="SCM001" Append="true" Modify="true" Print="true">服务商管理员</group>
            </access>
        </security>
        <security code="base.default" name="系统默认导航及其它功能" type="execute" group="base">
            <access verlist="4,6,1,2,3,5,0,">
                <group code="SCM001">服务商管理员</group>
                <group code="SCM101">总经理</group>
                <group code="SCM102">资料录入员</group>
                <group code="SCM103">业务经理</group>
                <group code="SCM104">区域经理</group>
                <group code="SCM105">业务员</group>
                <group code="SCM106">采购员</group>
                <group code="SCM107">仓管员</group>
                <group code="SCM108">财务</group>
                <group code="SCM199">网店会员</group>
                <group code="SCM201">老板</group>
                <group code="SCM202">店长</group>
                <group code="SCM203">销售员</group>
                <group code="SCM204">仓管员</group>
                <group code="SCM299">网店会员</group>
                <group code="SCM301">老板</group>
                <group code="SCM302">店长</group>
                <group code="SCM303">店员</group>
                <group code="SCM399">网店会员</group>
                <group code="SCM401">老板</group>
                <group code="SCM402">财务</group>
                <group code="SCM403">仓管</group>
                <group code="SCM404">总经理</group>
                <group code="SCM405">资料录入员</group>
                <group code="SCM406">业务经理</group>
                <group code="SCM407">区域经理</group>
                <group code="SCM408">业务</group>
                <group code="SCM409">采购</group>
                <group code="SCM410">生管</group>
                <group code="SCM411">物管</group>
                <group code="SCM412">研发</group>
                <group code="SCM413">生产部</group>
                <group code="SCM499">网店会员</group>
                <group code="SCM501">老板</group>
                <group code="SCM601">老板</group>
                <group code="SCM602">总经理</group>
                <group code="SCM603">业务经理</group>
                <group code="SCM604">业务员</group>
                <group code="SCM699">网店会员</group>
            </access>
        </security>
        <security code="base.account.update" type="record" name="更改我的密码" group="base">
            <access verlist="4,6,1,2,3,5,0,">
                <group code="SCM001">服务商管理员</group>
                <group code="SCM101">总经理</group>
                <group code="SCM102">资料录入员</group>
                <group code="SCM103">业务经理</group>
                <group code="SCM104">区域经理</group>
                <group code="SCM105">业务员</group>
                <group code="SCM106">采购员</group>
                <group code="SCM107">仓管员</group>
                <group code="SCM108">财务</group>
                <group code="SCM199">网店会员</group>
                <group code="SCM201">老板</group>
                <group code="SCM202">店长</group>
                <group code="SCM203">销售员</group>
                <group code="SCM204">仓管员</group>
                <group code="SCM299">网店会员</group>
                <group code="SCM301">老板</group>
                <group code="SCM302">店长</group>
                <group code="SCM303">店员</group>
                <group code="SCM399">网店会员</group>
                <group code="SCM401">老板</group>
                <group code="SCM402">财务</group>
                <group code="SCM403">仓管</group>
                <group code="SCM404">总经理</group>
                <group code="SCM405">资料录入员</group>
                <group code="SCM406">业务经理</group>
                <group code="SCM407">区域经理</group>
                <group code="SCM408">业务</group>
                <group code="SCM409">采购</group>
                <group code="SCM410">生管</group>
                <group code="SCM411">物管</group>
                <group code="SCM412">研发</group>
                <group code="SCM413">生产部</group>
                <group code="SCM499">网店会员</group>
                <group code="SCM501">老板</group>
                <group code="SCM601">老板</group>
                <group code="SCM602">总经理</group>
                <group code="SCM603">业务经理</group>
                <group code="SCM604">业务员</group>
                <group code="SCM699">网店会员</group>
            </access>
        </security>
        <security code="base.account.manage" type="record" name="用户帐号管理" group="base">
            <access verlist="4,6,1,2,3,5,0,">
                <group code="SCM001" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">服务商管理员</group>
                <group code="SCM101" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">总经理</group>
                <group code="SCM201" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM301" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM401" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM501" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM601" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
            </access>
        </security>
        <security code="base.product.manage" name="商品基本资料与库存管理" type="record" group="base">
            <access verlist="4,6,1,2,3,5,">
                <group code="SCM101" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">总经理</group>
                <group code="SCM102" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">资料录入员</group>
                <group code="SCM103">业务经理</group>
                <group code="SCM104">区域经理</group>
                <group code="SCM105">业务员</group>
                <group code="SCM106">采购员</group>
                <group code="SCM107">仓管员</group>
                <group code="SCM108">财务</group>
                <group code="SCM201" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM202" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">店长</group>
                <group code="SCM203">销售员</group>
                <group code="SCM204">仓管员</group>
                <group code="SCM205">财务专员</group>
                <group code="SCM301" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM302" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">店长</group>
                <group code="SCM303" Modify="true">店员</group>
                <group code="SCM401" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
                <group code="SCM402" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">财务</group>
                <group code="SCM403" Modify="true">仓管</group>
                <group code="SCM404">总经理</group>
                <group code="SCM405" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">资料录入员</group>
                <group code="SCM406">业务经理</group>
                <group code="SCM407">区域经理</group>
                <group code="SCM408">业务</group>
                <group code="SCM409">采购</group>
                <group code="SCM410">生管</group>
                <group code="SCM411">物管</group>
                <group code="SCM412" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">研发</group>
                <group code="SCM413">生产部</group>
                <group code="SCM501" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">老板</group>
            </access>
        </security>
        <security code="purchase.base.manage" name="厂商及采购基本资料设置" type="record" group="purchase">
            <access verlist="4,6,1,2,3,5,">
                <group code="SCM101" Append="true" Modify="true" Print="true" Final="true" Cancel="true" Recycle="true">总经理</group>
                <group code="SCM106" Append="true" Modify="true" Print="true">采购员</group>
